# Generated by Django 2.2.3 on 2020-10-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='value',
            field=models.CharField(default='+', max_length=10),
        ),
    ]
