# Generated by Django 2.2.3 on 2020-10-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
