# Generated by Django 2.2.3 on 2020-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiztaker_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('question_count', models.IntegerField(blank=True, default=30, null=True)),
                ('correct', models.IntegerField(blank=True, default=0, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='quiz',
        ),
    ]
