# Generated by Django 2.2.3 on 2020-10-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiztaker_taken_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='taken_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takenquiz', to='quiz.TakenQuiz'),
        ),
    ]
