# Generated by Django 2.2.3 on 2020-10-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20201021_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='taken_quiz',
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='quiztaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takenquiz', to='quiz.QuizTaker'),
        ),
    ]
