# Generated by Django 2.2.3 on 2020-10-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20201023_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='quizimage/'),
        ),
    ]
